# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Select Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
        
    - name: Install Dependencies
      run: |
        xcodebuild -resolvePackageDependencies
        
    - name: Build
      run: |
        xcodebuild clean build -scheme ios-app -destination "platform=iOS Simulator,name=iPhone 14 Pro"
